languageCode = "it"
languageName = "Italiano"
weight = 2
title = ""


[params]
  displayName = "Italiano"
  isoCode = "it"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/unimore.png"
  description = "Un potente, leggero tema per Hugo."

[params.author]
  name = "comefare.dscg.unimore.it"
  image = "img/unimore_logo.png"
  headline = "Guide e procedure informatiche interne del DSCG"
  bio = "Un potente, leggero tema per Hugo."
  links = [
    { facebook = "https://www.facebook.com/unimore.it" },
    { x-twitter = "https://twitter.com/unimore_univ?lang=it" },
    { instagram = "https://www.instagram.com/unimore_official" },
    { linkedin = "https://it.linkedin.com/edu/universit%C3%A0-degli-studi-di-modena-e-reggio-emilia-13877" },
    { youtube = "https://www.youtube.com/user/tvunimore" },
  ]
